spring.application.name=CampusEase
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/campease
spring.datasource.username=root
spring.datasource.password=1229

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


