spring.application.name=CampusEase
server.port=8080

# ✅ PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/campusease
spring.datasource.username=postgres
spring.datasource.password=1234

# ✅ Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ✅ Hibernate config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ✅ Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true